name: Feature Request
description: File a feature request.
title: "Feature"
labels: ["enhancement"]
body:
  - type: textarea
    id: what-needed
    attributes:
      label: What needed?
      description: Also tell us, what do you expect?
      placeholder: Tell us what you need!
      value: "A feature needed!"
    validations:
      required: true