name: Feature Request
description: File a feature request.
title: "Feature"
labels: ["enhancement"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you need!
      value: "A feature needed!"
    validations:
      required: true