name: Hotfix Report
description: File a hotfix report.
title: "Hotfix"
labels: ["hotfix"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A crucial bug happened!"
    validations:
      required: true