name: Enforce Branch Origins & Naming Convention

on:
  pull_request:

jobs:
  enforce-branch-origin:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Naming & Origin
        run: |
          base="${{ github.base_ref }}"
          head="${{ github.head_ref }}"

          # Ensure feature and bugfix branches start from develop
          if [[ "$head" =~ ^feature/\[#([0-9]+)\]-.*$ || "$head" =~ ^bugfix/\[#([0-9]+)\]-.*$ ]]; then
            if [[ "$base" != "develop" ]]; then
              echo "❌ Feature and bugfix branches must start from develop!"
              exit 1
            fi
          fi
          
          # Ensure hotfix branches start from main
          if [[ "$head" =~ ^hotfix/\[#([0-9]+)\]-.*$ ]]; then
            if [[ "$base" != "main" ]]; then
              echo "❌ Hotfix branches must start from main!"
              exit 1
            fi
          fi

      - name: Ensure Issue Number is Present in Branch Name
        run: |
          if [[ ! "$head" =~ ^(feature|bugfix|hotfix)/\[#([0-9]+)\]-.*$ ]]; then
            echo "❌ Branch name must follow the format: feature/[#issue-number]-issue-title"
            exit 1
          fi
