name: Restrict Merges
# comment
on:
  pull_request:

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Check target branch
        run: |
         if [[ "${{ github.base_ref }}" == "main" && ! ("${{ github.head_ref }}" == "develop" || "${{ github.head_ref }}" =~ ^[0-9]+-hotfix-.*$) ]]; then
            echo "❌ You can only merge 'develop' or '##-hotfix-*' branches into 'main'!"
            exit 1
          fi
